[package]
name = "syntwave"
version = "0.1.0"
authors = ["Morris Hansing <hansing@kth.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
rodio = "0.14.0"
vst = "0.2.1"